INSERT INTO Crypto_Types (name, symbol) VALUES
  ('Bitcoin','BTC'),
  ('Ethereum','ETH'),
  ('Bitcoin Cash','BCH'),
  ('Ripple','XRP'),
  ('Litecoin','LTC'),
  ('Dash','DASH'),
  ('NEO','NEO'),
  ('NEM','XEM'),
  ('Monero','XMR'),
  ('Ethereum Classic','ETC'),
  ('IOTA','MIOTA'),
  ('Qtum','QTUM'),
  ('Cardano','ADA'),
  ('OmiseGO','OMG'),
  ('Lisk','LSK'),
  ('Zcash','ZEC'),
  ('Stellar Lumens','XLM'),
  ('Tether','USDT'),
  ('BitConnect','BCC'),
  ('EOS','EOS'),
  ('Hshare','HSR'),
  ('Waves','WAVES'),
  ('Stratis','STRAT'),
  ('Ark','ARK'),
  ('Populous','PPT'),
  ('Komodo','KMD'),
  ('Bytecoin','BCN'),
  ('Ardor','ARDR'),
  ('Steem','STEEM'),
  ('BitShares','BTS'),
  ('Augur','REP'),
  ('SALT','SALT'),
  ('Binance Coin','BNB'),
  ('Decred','DCR'),
  ('MaidSafeCoin','MAID'),
  ('TenX','PAY'),
  ('Gas','GAS'),
  ('PIVX','PIVX'),
  ('Vertcoin','VTC'),
  ('Golem','GNT'),
  ('Kyber Network','KNC'),
  ('Electroneum','ETN'),
  ('Factom','FCT'),
  ('MonaCoin','MONA'),
  ('BitcoinDark','BTCD'),
  ('Veritaseum','VERI'),
  ('Basic Attenti...','BAT'),
  ('Walton','WTC'),
  ('Dogecoin','DOGE'),
  ('Siacoin','SC'),
  ('TRON','TRX'),
  ('Syscoin','SYS'),
  ('DigixDAO','DGD'),
  ('GameCredits','GAME'),
  ('Bytom','BTM'),
  ('Metaverse ETP','ETP'),
  ('Byteball Bytes','GBYTE'),
  ('Blocknet','BLOCK'),
  ('Status','SNT'),
  ('0x','ZRX'),
  ('MinexCoin','MNX'),
  ('GXShares','GXS'),
  ('Civic','CVC'),
  ('Iconomi','ICN'),
  ('Lykke','LKK'),
  ('Verge','XVG'),
  ('SingularDTV','SNGLS'),
  ('Aeternity','AE'),
  ('Metal','MTL'),
  ('DigiByte','DGB'),
  ('Pura','PURA'),
  ('Bancor','BNT'),
  ('Gnosis','GNO'),
  ('Raiden Networ...','RDN'),
  ('Bitquence','BQX'),
  ('ATMChain','ATM'),
  ('ChainLink','LINK'),
  ('VeChain','VEN'),
  ('Particl','PART'),
  ('Nxt','NXT'),
  ('FunFair','FUN'),
  ('Ripio Credit ...','RCN'),
  ('Monaco','MCO'),
  ('Power Ledger','POWR'),
  ('KuCoin Shares','KCS'),
  ('MobileGo','MGO'),
  ('Nexus','NXS'),
  ('ZenCash','ZEN'),
  ('AdEx','ADX'),
  ('Streamr DATAcoin','DATA'),
  ('ZCoin','XZC'),
  ('Cryptonex','CNX'),
  ('Edgeless','EDG'),
  ('Storj','STORJ'),
  ('Neblio','NEBL'),
  ('NAV Coin','NAV'),
  ('FairCoin','FAIR'),
  ('Ubiq','UBQ'),
  ('iExec RLC','RLC'),
  ('Loopring','LRC'),
  ('Aragon','ANT'),
  ('Counterparty','XCP'),
  ('Zeusshield','ZSC'),
  ('Bitdeal','BDL'),
  ('Kin','KIN'),
  ('Groestlcoin','GRS'),
  ('I/O Coin','IOC'),
  ('TaaS','TAAS'),
  ('Amber','AMB'),
  ('NoLimitCoin','NLC2'),
  ('SONM','SNM'),
  ('AirSwap','AST'),
  ('Request Network','REQ'),
  ('Open Trading ...','OTN'),
  ('Achain','ACT'),
  ('B3Coin','B3'),
  ('Centra','CTR'),
  ('Viacoin','VIA'),
  ('Peercoin','PPC'),
  ('Wings','WINGS'),
  ('Melon','MLN'),
  ('TokenCard','TKN'),
  ('Modum','MOD'),
  ('Enigma','ENG'),
  ('Gulden','NLG'),
  ('SuperNET','UNITY'),
  ('Everex','EVX'),
  ('Quantum Resis...','QRL'),
  ('ICOS','ICOS'),
  ('PotCoin','POT'),
  ('Decentraland','MANA'),
  ('Dentacoin','DCN'),
  ('Cofound.it','CFI'),
  ('ReddCoin','RDD'),
  ('Rise','RISE'),
  ('Moeda Loyalty...','MDA'),
  ('LEOcoin','LEO'),
  ('CloakCoin','CLOAK'),
  ('Emercoin','EMC'),
  ('Viberate','VIB'),
  ('FirstBlood','1ST'),
  ('Pillar','PLR'),
  ('BitBay','BAY'),
  ('Substratum','SUB'),
  ('Elastic','XEL'),
  ('LBRY Credits','LBC'),
  ('district0x','DNT'),
  ('MCAP','MCAP'),
  ('ATBCoin','ATB'),
  ('Skycoin','SKY'),
  ('WeTrust','TRST'),
  ('Tierion','TNT'),
  ('Aeon','AEON'),
  ('Red Pulse','RPX'),
  ('PayPie','PPP'),
  ('OKCash','OK'),
  ('XPlay','XPA'),
  ('DomRaider','DRT'),
  ('SIBCoin','SIB'),
  ('Diamond','DMD'),
  ('Xaurum','XAUR'),
  ('Cindicator','CND'),
  ('DECENT','DCT'),
  ('Crown','CRW'),
  ('Paragon','PRG'),
  ('Namecoin','NMC'),
  ('Eidoo','EDO'),
  ('CoinDash','CDT'),
  ('SmartCash','SMART'),
  ('Revain','R'),
  ('Feathercoin','FTC'),
  ('ION','ION'),
  ('Triggers','TRIG'),
  ('Stox','STX'),
  ('Safe Exchange...','SAFEX'),
  ('Rubycoin','RBY'),
  ('bitqy','BQ'),
  ('Target Coin','TGT'),
  ('Agrello','DLT'),
  ('Etheroll','DICE'),
  ('Monetha','MTH'),
  ('Pepe Cash','PEPECASH'),
  ('BitDice','CSNO'),
  ('Blackmoon Crypto','BMC'),
  ('BlackCoin','BLK'),
  ('Nebulas Token','NAS'),
  ('RaiBlocks','XRB'),
  ('Aventus','AVT'),
  ('Chronobank','TIME'),
  ('The ChampCoin','TCC'),
  ('GridCoin','GRC'),
  ('Mothership','MSP'),
  ('DigitalNote','XDN'),
  ('ToaCoin','TOA'),
  ('Santiment Net...','SAN'),
  ('VeriCoin','VRC'),
  ('Einsteinium','EMC2'),
  ('Expanse','EXP'),
  ('Rialto','XRL'),
  ('Humaniq','HMQ');
