START TRANSACTION;

INSERT INTO Crypto_Types (name, symbol) VALUES
  ('Bitcoin','BTC'),
  ('Ethereum','ETH'),
  ('Bitcoin Cash','BCH'),
  ('Ripple','XRP'),
  ('Litecoin','LTC'),
  ('Dash','DASH'),
  ('NEO','NEO'),
  ('NEM','XEM'),
  ('Monero','XMR'),
  ('Ethereum Classic','ETC'),
  ('IOTA','MIOTA'),
  ('Qtum','QTUM'),
  ('Cardano','ADA'),
  ('OmiseGO','OMG'),
  ('Lisk','LSK'),
  ('Zcash','ZEC'),
  ('Stellar Lumens','XLM'),
  ('Tether','USDT'),
  ('BitConnect','BCC'),
  ('EOS','EOS'),
  ('Hshare','HSR'),
  ('Waves','WAVES'),
  ('Stratis','STRAT'),
  ('Ark','ARK'),
  ('Populous','PPT'),
  ('Komodo','KMD'),
  ('Bytecoin','BCN'),
  ('Ardor','ARDR'),
  ('Steem','STEEM'),
  ('BitShares','BTS'),
  ('Augur','REP'),
  ('SALT','SALT'),
  ('Binance Coin','BNB'),
  ('Decred','DCR'),
  ('MaidSafeCoin','MAID'),
  ('TenX','PAY'),
  ('Gas','GAS'),
  ('PIVX','PIVX'),
  ('Vertcoin','VTC'),
  ('Golem','GNT'),
  ('Kyber Network','KNC'),
  ('Electroneum','ETN'),
  ('Factom','FCT'),
  ('MonaCoin','MONA'),
  ('BitcoinDark','BTCD'),
  ('Veritaseum','VERI'),
  ('Walton','WTC'),
  ('Dogecoin','DOGE'),
  ('Siacoin','SC'),
  ('TRON','TRX'),
  ('Syscoin','SYS'),
  ('DigixDAO','DGD'),
  ('GameCredits','GAME'),
  ('Bytom','BTM'),
  ('Metaverse ETP','ETP'),
  ('Byteball Bytes','GBYTE'),
  ('Blocknet','BLOCK'),
  ('Status','SNT'),
  ('0x','ZRX'),
  ('MinexCoin','MNX'),
  ('GXShares','GXS'),
  ('Civic','CVC'),
  ('Iconomi','ICN'),
  ('Lykke','LKK'),
  ('Verge','XVG'),
  ('SingularDTV','SNGLS'),
  ('Aeternity','AE'),
  ('Metal','MTL'),
  ('DigiByte','DGB'),
  ('Pura','PURA'),
  ('Bancor','BNT'),
  ('Gnosis','GNO'),
  ('Raiden Networ...','RDN'),
  ('Bitquence','BQX'),
  ('ATMChain','ATM'),
  ('ChainLink','LINK'),
  ('VeChain','VEN'),
  ('Particl','PART'),
  ('Nxt','NXT'),
  ('FunFair','FUN'),
  ('Monaco','MCO');

COMMIT;
